/-
Copyright (c) 2026 Kepler-Hurrwitz contributors.
Auto-generated by export_resonanz_lean_audit.py — do not hand-edit matrix blocks.

Phase A: JSON survivor list + shift rule ⇒ MwFromShift = MwJson over Rat.
Phase B: spectral witnesses (nilpotency / rho lower bound).
Epistemics: finite audit; not a Collatz proof.
-/

import Mathlib.Data.Matrix.Basic
import Mathlib.Data.Rat.Defs
import Mathlib.Tactic
namespace KeplerHurwitz.Collatz.ResonanzOperatorAudit_L8C10


open Matrix

/-- Word encoded MSB-first as Nat (`int(word,2)`). -/
abbrev WordNat := Nat

/-- `u[1:] = v[:-1]` for bitstrings of length 8. -/
def shiftCompatible (u v : WordNat) : Bool :=
  decide (u % (2 ^ (8 - 1)) = v / 2)

def shiftWeight (v : WordNat) : Rat :=
  if v % 2 = 0 then (1 : Rat) / 2 else (3 : Rat) / 2

def mwFromWords {n : Nat} (words : Fin n → WordNat) : Matrix (Fin n) (Fin n) Rat :=
  Matrix.of fun i j =>
    if shiftCompatible (words i) (words j) then shiftWeight (words j) else 0


/-! ## Instance L8C10: C=10.0, L=8, n=18 -/

def n_L8C10 : Nat := 18
def wordsArr_L8C10 : Array WordNat := #[55, 95, 111, 115, 125, 151, 171, 174, 185, 190, 207, 213, 223, 231, 235, 245, 250, 252]
def words_L8C10 : Fin 18 → WordNat :=
  fun i => wordsArr_L8C10[i.val]!
def MwJsonArr_L8C10 : Array Rat := #[0, 0, (3 : Rat) / 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (1 : Rat) / 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (3 : Rat) / 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (3 : Rat) / 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (1 : Rat) / 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (3 : Rat) / 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (3 : Rat) / 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (3 : Rat) / 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (1 : Rat) / 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (3 : Rat) / 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (3 : Rat) / 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (3 : Rat) / 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
def MwJson_L8C10 : Matrix (Fin 18) (Fin 18) Rat :=
  Matrix.of fun i j => MwJsonArr_L8C10[i.val * 18 + j.val]!
def MwLean_L8C10 : Matrix (Fin 18) (Fin 18) Rat :=
  mwFromWords words_L8C10

/-- Phase A: Lean shift reconstruction equals exported JSON matrix. -/
theorem Mw_identity_L8C10 : MwLean_L8C10 = MwJson_L8C10 := by
  native_decide


/-- Phase B: acyclic shift — nilpotent of index ≤ 8. -/
theorem Mw_nilpotent_L8C10 :
    MwLean_L8C10 ^ 8 = 0 := by
  rw [Mw_identity_L8C10]
  native_decide

end KeplerHurwitz.Collatz.ResonanzOperatorAudit_L8C10
