/-
Copyright (c) 2026 Kepler-Hurrwitz contributors.
Auto-generated by export_resonanz_lean_audit.py — do not hand-edit matrix blocks.

Phase A: JSON survivor list + shift rule ⇒ MwFromShift = MwJson over Rat.
Phase B: spectral witnesses (nilpotency / rho lower bound).
Epistemics: finite audit; not a Collatz proof.
-/

import Mathlib.Data.Matrix.Basic
import Mathlib.Data.Rat.Defs
import Mathlib.Tactic
namespace KeplerHurwitz.Collatz.ResonanzOperatorAudit_L8C12


open Matrix

/-- Word encoded MSB-first as Nat (`int(word,2)`). -/
abbrev WordNat := Nat

/-- `u[1:] = v[:-1]` for bitstrings of length 8. -/
def shiftCompatible (u v : WordNat) : Bool :=
  decide (u % (2 ^ (8 - 1)) = v / 2)

def shiftWeight (v : WordNat) : Rat :=
  if v % 2 = 0 then (1 : Rat) / 2 else (3 : Rat) / 2

def mwFromWords {n : Nat} (words : Fin n → WordNat) : Matrix (Fin n) (Fin n) Rat :=
  Matrix.of fun i j =>
    if shiftCompatible (words i) (words j) then shiftWeight (words j) else 0


/-! ## Instance L8C12: C=12.0, L=8, n=3 -/

def n_L8C12 : Nat := 3
def wordsArr_L8C12 : Array WordNat := #[190, 223, 250]
def words_L8C12 : Fin 3 → WordNat :=
  fun i => wordsArr_L8C12[i.val]!
def MwJsonArr_L8C12 : Array Rat := #[0, 0, 0, (1 : Rat) / 2, 0, 0, 0, 0, 0]
def MwJson_L8C12 : Matrix (Fin 3) (Fin 3) Rat :=
  Matrix.of fun i j => MwJsonArr_L8C12[i.val * 3 + j.val]!
def MwLean_L8C12 : Matrix (Fin 3) (Fin 3) Rat :=
  mwFromWords words_L8C12

/-- Phase A: Lean shift reconstruction equals exported JSON matrix. -/
theorem Mw_identity_L8C12 : MwLean_L8C12 = MwJson_L8C12 := by
  native_decide


/-- Phase B: acyclic shift — nilpotent of index ≤ 2. -/
theorem Mw_nilpotent_L8C12 :
    MwLean_L8C12 ^ 2 = 0 := by
  rw [Mw_identity_L8C12]
  native_decide

end KeplerHurwitz.Collatz.ResonanzOperatorAudit_L8C12
