

# This file was *autogenerated* from the file scripts/_debug_equiv.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_12 = Integer(12)
import sys
sys.argv = ['debug']
exec(open('scripts/invariant_subspaces_a4_toy.sage').read().split('if __name__')[_sage_const_0 ])

payload = _build_a5_geo_projectors()
data = payload['data']
vertices = data['vertices']
gen_group = data['gen_group']
groups, order_labels, _ = _build_canonical_eabc_embedding(vertices)
canonical_code = _label_code_vector(groups, order_labels)
passing = _collect_passing_toy_label_codes(vertices)
perms = list(SymmetricGroup(_sage_const_4 ))

print('A5 order', gen_group.order())

for name, toy_code in passing[:_sage_const_5 ]:
    found = False
    for g in gen_group.list():
        images = tuple(g(i + _sage_const_1 ) - _sage_const_1  for i in range(_sage_const_12 ))
        # _permuted_label_code: out[images[i]] = canonical[i]
        pulled = _permuted_label_code(canonical_code, images)
        for tau in perms:
            mapped = tuple(_apply_channel_perm(tau, c) for c in pulled)
            if mapped == toy_code:
                print(name, 'FOUND permuted_label_code + tau')
                found = True
                break
        if found:
            break
    if not found:
        # Lean forward: toy[v] = tau(canonical[sigma(v)]) with sigma from A5
        for g in gen_group.list():
            for tau in perms:
                ok = all(
                    toy_code[v] == _apply_channel_perm(tau, canonical_code[g(v + _sage_const_1 ) - _sage_const_1 ])
                    for v in range(_sage_const_12 )
                )
                if ok:
                    print(name, 'FOUND lean forward with A5')
                    found = True
                    break
            if found:
                break
    print(name, 'found', found)

