# -*- coding: utf-8 -*-
#!/usr/bin/env sage
"""
Symbolische W_N-Zyklen fuer Aharonov-Bohm / Bockstein-Braiding auf Z_N x Z_N.

[B] Toy Layer — kein physikalischer Claim. Defensiv: phase(W_N) in mu_N,
d.h. phase(W_N)^N = 1; nicht pauschal W_N^N = I als Operatoridentitaet.
Siehe docs/bockstein_braiding_layer.md und scripts/bockstein_braiding_symbolic.sage.

Geschlossene unitaere Sequenz:
    W_N(X, Y) = (Y^{-1} X^{-1})^N (Y X)^N

Modi:
    verify      Standard: Gruppenring + Heisenberg-Torus, N-Potenz, Linearitaet
    group_ring  Nur Z[A,B]/(A^N-1, B^N-1)
    heisenberg  Magnetische Translationsalgebra (HV = zeta VH)
    lattice_2d  2D-Gitter mit lokaler Kommutatordichte K(P,Q;a)

Ausfuehrung:
    sage scripts/aharonov_bohm_bockstein_w_cycles.sage
    sage scripts/aharonov_bohm_bockstein_w_cycles.sage lattice_2d
"""


# This file was *autogenerated* from the file scripts/aharonov_bohm_bockstein_w_cycles.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_1en12 = RealNumber('1e-12'); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7)
from sage.all import *
import sys


def torus_group_ring(N, base=ZZ):
    """Gruppenring Z[A,B]/(A^N-1, B^N-1) ~ Z[Z_N x Z_N]."""
    G = AbelianGroup([N, N])
    R = G.algebra(base)
    A = R.monomial(G.gens()[_sage_const_0 ])
    B = R.monomial(G.gens()[_sage_const_1 ])
    return R, A, B


def W_N_element(X, Y, N):
    """W_N(X,Y) = (Y^{-1} X^{-1})^N (Y X)^N."""
    return (Y**(-_sage_const_1 ) * X**(-_sage_const_1 ))**N * (Y * X)**N


def heisenberg_matrices(N, flux=_sage_const_1 ):
    """
    Magnetische Translationsalgebra auf Z_N:
    X = horizontaler Shift, Y = Phasenoperator mit XY = zeta^flux YX.
    """
    K = CyclotomicField(N)
    zeta = K.gen()
    twist = zeta**flux
    MS = MatrixSpace(K, N, N)
    I = MS.identity_matrix()
    X = MS([[_sage_const_1  if j == (i - _sage_const_1 ) % N else _sage_const_0  for j in range(N)] for i in range(N)])
    Y = MS.diagonal_matrix([twist**k for k in range(N)])
    return MS, X, Y, zeta, twist, I


def is_central_scalar(M, I, tol=_sage_const_1en12 ):
    """Prueft, ob M = lambda I (skalar-zentral)."""
    if M != M.parent()(M[_sage_const_0 , _sage_const_0 ]) * I:
        return False, None
    return True, M[_sage_const_0 , _sage_const_0 ]


def verify_group_ring(N, alphas=(_sage_const_2 , _sage_const_3 )):
    """Im kommutativen Gruppenring ist W_N trivial (= 1)."""
    R, A, B = torus_group_ring(N)
    one = R.one()
    W = W_N_element(A, B, N)
    lin = []
    for alpha in alphas:
        if alpha >= N:
            continue
        Wa = W_N_element(A**alpha, B, N)
        lin.append((alpha, Wa == W**alpha))
    return {
        "N": N,
        "W": W,
        "W_is_one": W == one,
        "W_power_N_is_one": W**N == one,
        "linearity": lin,
    }


def verify_heisenberg(N, flux=_sage_const_1 , alphas=(_sage_const_2 , _sage_const_3 ), tol=_sage_const_1en12 ):
    """Nicht-kommutativer Torus: W_N zentral; phase(W_N) in mu_N; Linearitaet.

    Hauptcheck: phase(W_N)^N = 1. W_power_N_is_one ist nur numerischer Skalar-Folgecheck.
    """
    MS, X, Y, zeta, twist, I = heisenberg_matrices(N, flux=flux)
    # Kommutator einer Plaquette: XY X^{-1} Y^{-1} = twist^{-1} I
    comm = X * Y * X.inverse() * Y.inverse()
    holonomy = twist**(-_sage_const_1 )
    ok_comm = comm == holonomy * I

    W = W_N_element(X, Y, N)
    central, phase = is_central_scalar(W, I)
    phase_power_n_is_one = phase is not None and abs(phase**N - _sage_const_1 ) < tol
    w_power_n_is_identity = central and W**N == I

    lin = []
    for alpha in alphas:
        if alpha >= N:
            continue
        W_base = W_N_element(X, Y, N)
        W_alpha = W_N_element(X**alpha, Y, N)
        lin.append((alpha, W_alpha == W_base**alpha))

    return {
        "N": N,
        "flux": flux,
        "plaquette_commutator_ok": ok_comm,
        "plaquette_holonomy": holonomy,
        "W_central": central,
        "W_phase": phase,
        "phase_power_N_is_one": phase_power_n_is_one,
        "W_power_N_is_one": w_power_n_is_identity,
        "quantization_ok": central and phase_power_n_is_one,
        "linearity": lin,
    }


def K_plaquette(P, Q, a, N):
    """
    Lokale Kommutatordichte K(P,Q;a) auf Z_N x Z_N (homogenes Modell).

    Fuer Bockstein-Braiding mit Parameter a: jede Plaquette traegt denselben
    Flux-Exponenten a; raeumliche Variation ist hier P+Q mod N als Probe.
    """
    return Integer((a * (P + Q)) % N)


def K_plaquette_variable(P, Q, a_spec, N):
    """K(P,Q) mit homogenem a (int) oder raeumlich variierendem a(P,Q) (Callable)."""
    if callable(a_spec):
        return Integer(a_spec(P, Q) % N)
    return K_plaquette(P, Q, a_spec, N)


def a_PQ_default(P, Q, N):
    """Standardprobe a(P,Q) = (P + 2Q) mod N."""
    return Integer((P + _sage_const_2  * Q) % N)


def staircase_holonomy_mod_N(a_spec, N):
    """Bockstein-Treppe: sum_{m=0}^{N-1} K(m,m) mod N (Hsin-Chen, Gl. 76)."""
    return Integer(sum(K_plaquette_variable(m, m, a_spec, N) for m in range(N)) % N)


def grid_holonomy_mod_N(a_spec, N):
    """Summe aller Plaquette-Beitraege mod N."""
    return Integer(
        sum(K_plaquette_variable(P, Q, a_spec, N) for P in range(N) for Q in range(N)) % N
    )


def lattice_2d_variable_demo(N, a_spec, tol=_sage_const_1en12 ):
    """Vergleich Bockstein-Treppe vs. Gitter-Summe vs. globales W_N."""
    stair = staircase_holonomy_mod_N(a_spec, N)
    grid = grid_holonomy_mod_N(a_spec, N)
    eff_flux = Integer(a_spec if not callable(a_spec) else stair)

    MS, X, Y, zeta, twist, I = heisenberg_matrices(N, flux=int(eff_flux))
    W = W_N_element(X, Y, N)
    central, phase = is_central_scalar(W, I)
    phase_power_n_is_one = phase is not None and abs(phase**N - _sage_const_1 ) < tol
    w_power_n_is_identity = central and W**N == I

    W_a2 = W_N_element(*heisenberg_matrices(N, flux=int(_sage_const_2  * eff_flux % N))[_sage_const_1 :_sage_const_3 ], N)
    _, phase_a2 = is_central_scalar(W_a2, I)

    return {
        "N": N,
        "staircase_holonomy_mod_N": stair,
        "grid_holonomy_mod_N": grid,
        "effective_flux": eff_flux,
        "W_phase": phase,
        "W_central": central,
        "phase_power_N_is_one": phase_power_n_is_one,
        "W_power_N_is_one": w_power_n_is_identity,
        "quantization_ok": central and phase_power_n_is_one,
        "linearity_flux": phase_a2 == phase**_sage_const_2  if phase is not None else False,
    }


def lattice_2d_demo(N, a=_sage_const_1 , flux=None, tol=_sage_const_1en12 ):
    """
    2D-Gitter: Summe der lokalen K(P,Q;a) ueber ein N x N Plaquetten-Gitter.

    Die effektive Holonomie eines contractible W_N-Zyklus wird mit der
    magnetischen Translationsalgebra verglichen.
    """
    if flux is None:
        flux = a
    MS, X, Y, zeta, twist, I = heisenberg_matrices(N, flux=flux)

    K_sum = sum(K_plaquette(P, Q, a, N) for P in range(N) for Q in range(N))
    K_sum_mod = K_sum % N

    W = W_N_element(X, Y, N)
    central, phase = is_central_scalar(W, I)
    phase_power_n_is_one = phase is not None and abs(phase**N - _sage_const_1 ) < tol
    w_power_n_is_identity = central and W**N == I

    # Erwartete zentrale Phase: zeta^{N * flux} = 1; Linearitaet in a testen
    W_a2 = W_N_element(
        *heisenberg_matrices(N, flux=_sage_const_2  * flux)[_sage_const_1 :_sage_const_3 ],
        N,
    )
    _, phase_a2 = is_central_scalar(W_a2, I)

    return {
        "N": N,
        "a": a,
        "flux": flux,
        "K_sum_mod_N": K_sum_mod,
        "sample_K": [(P, Q, K_plaquette(P, Q, a, N)) for P in range(min(N, _sage_const_3 )) for Q in range(min(N, _sage_const_3 ))],
        "W_phase": phase,
        "W_central": central,
        "phase_power_N_is_one": phase_power_n_is_one,
        "W_power_N_is_one": w_power_n_is_identity,
        "quantization_ok": central and phase_power_n_is_one,
        "double_flux_phase": phase_a2,
        "linearity_flux": phase_a2 == phase**_sage_const_2  if phase is not None else False,
    }


def print_group_ring(results):
    print("=== Gruppenring Z[A,B]/(A^N-1, B^N-1) ===")
    for r in results:
        print(
            f"N={r['N']}: W=1? {r['W_is_one']}, "
            f"W^N=1? {r['W_power_N_is_one']}, "
            f"Linearitaet {r['linearity']}"
        )


def print_heisenberg(results):
    print("=== Heisenberg-Torus (XY = zeta^flux YX) ===")
    for r in results:
        print(
            f"N={r['N']}, flux={r['flux']}: "
            f"Plaquette-Comm OK? {r['plaquette_commutator_ok']}, "
            f"Holonomie={r['plaquette_holonomy']}, "
            f"W zentral? {r['W_central']}, W-Phase={r['W_phase']}, "
            f"phase(W_N) in mu_N? {r['phase_power_N_is_one']}, "
            f"(numerisch W^N=I: {r['W_power_N_is_one']}), "
            f"Linearitaet {r['linearity']}"
        )


def print_lattice_2d(results):
    print("=== 2D-Gitter: lokale K(P,Q;a) ===")
    for r in results:
        print(f"N={r['N']}, a={r['a']}, flux={r['flux']}:")
        print(f"  sum_PQ K mod N = {r['K_sum_mod_N']}")
        print(f"  Stichprobe K(P,Q;a): {r['sample_K']}")
        print(
            f"  W-Phase={r['W_phase']}, phase(W_N) in mu_N? {r['phase_power_N_is_one']}, "
            f"(numerisch W^N=I: {r['W_power_N_is_one']}), "
            f"2*flux-Linearitaet? {r['linearity_flux']}"
        )


def run_verify(ns=(_sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_5 )):
    gr = [verify_group_ring(N) for N in ns]
    hs = [verify_heisenberg(N, flux=_sage_const_1 ) for N in ns]
    print_group_ring(gr)
    print()
    print_heisenberg(hs)
    all_ok = all(
        r.get("quantization_ok", r["W_power_N_is_one"])
        and all(x[_sage_const_1 ] for x in r["linearity"])
        for r in hs
    ) and all(
        r["W_power_N_is_one"] and all(x[_sage_const_1 ] for x in r["linearity"])
        for r in gr
    )
    print()
    print(f"Alle Checks bestanden: {all_ok}")
    return all_ok


def run_group_ring(ns=(_sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_5 , _sage_const_7 )):
    print_group_ring([verify_group_ring(N) for N in ns])


def run_heisenberg(ns=(_sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_5 , _sage_const_7 )):
    print_heisenberg([verify_heisenberg(N, flux=_sage_const_1 ) for N in ns])


def run_lattice_2d():
    results = []
    for N in [_sage_const_3 , _sage_const_4 , _sage_const_5 ]:
        for a in [_sage_const_1 , _sage_const_2 ]:
            if a >= N:
                continue
            results.append(lattice_2d_demo(N, a=a))
    print_lattice_2d(results)


def print_lattice_2d_variable(results):
    print("=== 2D-Gitter: variabler Flux a(P,Q) ===")
    for r in results:
        print(
            f"N={r['N']}: Treppe={r['staircase_holonomy_mod_N']}, "
            f"Gitter={r['grid_holonomy_mod_N']}, flux={r['effective_flux']}, "
            f"W-Phase={r['W_phase']}, phase(W_N) in mu_N? {r['phase_power_N_is_one']}, "
            f"(numerisch W^N=I: {r['W_power_N_is_one']})"
        )


def run_lattice_2d_variable():
    results = []
    for N in [_sage_const_3 , _sage_const_4 , _sage_const_5 ]:
        results.append(lattice_2d_variable_demo(N, a_spec=lambda P, Q, N=N: a_PQ_default(P, Q, N)))
    print_lattice_2d_variable(results)


def main():
    mode = "verify"
    if len(sys.argv) > _sage_const_1 :
        mode = sys.argv[_sage_const_1 ].strip().lower()

    if mode == "verify":
        ok = run_verify()
        if not ok:
            raise SystemExit(_sage_const_1 )
    elif mode == "group_ring":
        run_group_ring()
    elif mode == "heisenberg":
        run_heisenberg()
    elif mode == "lattice_2d":
        run_lattice_2d()
    elif mode == "lattice_2d_variable":
        run_lattice_2d_variable()
    else:
        print("Unbekannter Modus. Nutze: verify | group_ring | heisenberg | lattice_2d | lattice_2d_variable")
        raise SystemExit(_sage_const_2 )


if __name__ == "__main__":
    main()

