# -*- coding: utf-8 -*-
#!/usr/bin/env sage

"""
Toy-Check fuer invariante Unterraeume und Summenzerlegung.

Modell:
- Gruppe: A4 oder A5 als Permutationsgruppe auf n Punkten
- Darstellung: Permutationsdarstellung auf Q^n

Zusatzmodus:
- a5_geo: rotational icosahedral/dodecahedral symmetry group, isomorphic to A5.
  This is NOT the full Ih group (no inversion/reflections).
"""


# This file was *autogenerated* from the file scripts/invariant_subspaces_a4_toy.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_3 = Integer(3); _sage_const_1p0 = RealNumber('1.0'); _sage_const_2 = Integer(2); _sage_const_60 = Integer(60); _sage_const_5 = Integer(5); _sage_const_12 = Integer(12); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_4 = Integer(4); _sage_const_1en7 = RealNumber('1e-7'); _sage_const_20260703 = Integer(20260703); _sage_const_6 = Integer(6); _sage_const_9 = Integer(9); _sage_const_1en9 = RealNumber('1e-9'); _sage_const_0p0 = RealNumber('0.0'); _sage_const_8 = Integer(8); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11)
from sage.all import *
import sys
from itertools import permutations as it_permutations
import random as py_random


def permutation_matrix_qn(perm, n):
    """nxn-Permutationsmatrix ueber QQ fuer eine Permutation."""
    M = matrix(QQ, n, n, _sage_const_0 )
    for i in range(_sage_const_1 , n + _sage_const_1 ):
        M[perm(i) - _sage_const_1 , i - _sage_const_1 ] = _sage_const_1 
    return M


def is_invariant_subspace(mats, basis_vectors):
    """
    Prueft Invarianz eines Unterraums span(basis_vectors) unter allen Matrizen.
    """
    if not basis_vectors:
        return True
    B = matrix(QQ, basis_vectors).transpose()
    W = B.column_space()
    for A in mats:
        for v in basis_vectors:
            if A * vector(QQ, v) not in W:
                return False
    return True


def print_subspace(name, basis_vectors):
    print(f"{name}:")
    for v in basis_vectors:
        print(f"  {tuple(v)}")


def build_sumzero_basis(n):
    """
    Basis von {x in Q^n | Summe(x)=0}: e_i - e_n fuer i=1..n-1
    """
    basis = []
    for i in range(n - _sage_const_1 ):
        v = [_sage_const_0 ] * n
        v[i] = _sage_const_1 
        v[n - _sage_const_1 ] = -_sage_const_1 
        basis.append(vector(QQ, v))
    return basis


def run_perm_case(n):
    G = AlternatingGroup(n)
    mats = [permutation_matrix_qn(g, n) for g in G.list()]

    print(f"Gruppe A{n}, |G| = {G.order()}")
    print(f"Anzahl Darstellungsoperatoren: {len(mats)}")

    one = vector(QQ, [_sage_const_1 ] * n)
    W_triv_basis = [one]
    W_sumzero_basis = build_sumzero_basis(n)

    print_subspace("W_triv (trivialer Unterraum)", W_triv_basis)
    print_subspace("W_sumzero (Summe = 0)", W_sumzero_basis)

    inv_triv = is_invariant_subspace(mats, W_triv_basis)
    inv_sumzero = is_invariant_subspace(mats, W_sumzero_basis)

    print(f"Invariant W_triv: {inv_triv}")
    print(f"Invariant W_sumzero: {inv_sumzero}")

    V = VectorSpace(QQ, n)
    W_triv = span(W_triv_basis)
    W_sumzero = span(W_sumzero_basis)

    inter_dim = W_triv.intersection(W_sumzero).dimension()
    sum_space = W_triv + W_sumzero
    sum_dim = sum_space.dimension()

    print(f"dim(W_triv ∩ W_sumzero) = {inter_dim}")
    print(f"dim(W_triv + W_sumzero) = {sum_dim}")
    print(f"dim(V) = {V.dimension()}")
    print(
        f"Direktsummen-Check (dim={n} und Schnitt=0): "
        f"{sum_dim == n and inter_dim == _sage_const_0 }"
    )

    inv_sum = is_invariant_subspace(mats, sum_space.basis())
    print(f"Invariant der Summe W_triv + W_sumzero: {inv_sum}")


def _round_key(v, digits=_sage_const_10 ):
    return tuple(round(float(x), digits) for x in v)


def _vertex_index_map(vertices):
    return {_round_key(v): i for i, v in enumerate(vertices)}


def _nearest_vertex_index(v, vertices, tol=_sage_const_1en8 ):
    best_i = None
    best_d = None
    for i, w in enumerate(vertices):
        d = (v - w).norm()
        if best_d is None or d < best_d:
            best_d = d
            best_i = i
    if best_d is not None and best_d < tol:
        return best_i
    return None


def _perm_from_images(images):
    # Sage permutations are 1-based
    return Permutation([i + _sage_const_1  for i in images])


def _perm_matrix_qn_from_images(images, n):
    M = matrix(QQ, n, n, _sage_const_0 )
    for i, j in enumerate(images):
        M[j, i] = _sage_const_1 
    return M


def _rotation_from_base_to_target(B, T):
    return T * B.inverse()


def _is_rotation(M, tol=_sage_const_1en8 ):
    I = identity_matrix(RDF, _sage_const_3 )
    ortho = (M.transpose() * M - I).norm() < tol
    det_ok = abs(M.det() - _sage_const_1p0 ) < tol
    return ortho and det_ok


def _images_under_rotation(M, vertices, tol=_sage_const_1en8 ):
    images = []
    for v in vertices:
        w = M * v
        idx = _nearest_vertex_index(w, vertices, tol=tol)
        if idx is None:
            return None
        images.append(idx)
    # ensure permutation
    if len(set(images)) != len(vertices):
        return None
    return images


def _generate_rotation_candidates(vertices):
    # fix a linearly independent base triple
    base = [vertices[_sage_const_0 ], vertices[_sage_const_1 ], vertices[_sage_const_2 ]]
    if matrix(RDF, _sage_const_3 , _sage_const_3 , [x for v in base for x in v]).det() == _sage_const_0 :
        raise RuntimeError("Base triple is linearly dependent.")
    B = matrix(RDF, _sage_const_3 , _sage_const_3 , [x for v in base for x in v]).transpose()

    rot_by_perm = {}
    for i, j, k in it_permutations(range(len(vertices)), int(_sage_const_3 )):
        T = matrix(RDF, _sage_const_3 , _sage_const_3 , [x for v in [vertices[i], vertices[j], vertices[k]] for x in v]).transpose()
        if abs(T.det()) < _sage_const_1en8 :
            continue
        M = _rotation_from_base_to_target(B, T)
        if not _is_rotation(M):
            continue
        images = _images_under_rotation(M, vertices)
        if images is None:
            continue
        key = tuple(images)
        if key not in rot_by_perm:
            rot_by_perm[key] = M
    return rot_by_perm


def _find_generators_of_order_60(rot_perm_keys):
    keys = list(rot_perm_keys)
    id_key = tuple(range(len(keys[_sage_const_0 ])))
    perms = [_perm_from_images(k) for k in keys if k != id_key]
    for p in perms:
        G = PermutationGroup([p])
        if G.order() == _sage_const_60 :
            return [p], G
    for a in range(len(perms)):
        for b in range(a + _sage_const_1 , len(perms)):
            G = PermutationGroup([perms[a], perms[b]])
            if G.order() == _sage_const_60 :
                return [perms[a], perms[b]], G
    return None, None


def build_a5_geo_data():
    # Icosahedron vertices with golden ratio
    phi = (_sage_const_1  + sqrt(RDF(_sage_const_5 ))) / _sage_const_2 
    verts = []
    for s1 in (-_sage_const_1 , _sage_const_1 ):
        for s2 in (-_sage_const_1 , _sage_const_1 ):
            verts.append(vector(RDF, [_sage_const_0 , s1, s2 * phi]))
            verts.append(vector(RDF, [s1, s2 * phi, _sage_const_0 ]))
            verts.append(vector(RDF, [s1 * phi, _sage_const_0 , s2]))

    # Deduplicate (there should be exactly 12)
    uniq = {}
    for v in verts:
        uniq[_round_key(v)] = v
    vertices = list(uniq.values())
    if len(vertices) != _sage_const_12 :
        raise RuntimeError(f"Expected 12 vertices, got {len(vertices)}")

    rot_by_perm = _generate_rotation_candidates(vertices)
    rot_perms = list(rot_by_perm.keys())
    n = len(vertices)

    if not rot_perms:
        raise RuntimeError("No geometric rotation symmetries found.")

    # Group from all found rotations
    all_group = PermutationGroup([_perm_from_images(p) for p in rot_perms])
    all_order = all_group.order()

    gens, gen_group = _find_generators_of_order_60(rot_perms)
    if gen_group is None:
        raise RuntimeError("Could not find a small generator set of order 60.")

    # Permutation representation on Q^12 for selected generators
    gen_images = []
    for g in gens:
        # convert Sage permutation back to image tuple
        # g(i+1) is image in 1..n
        gen_images.append(tuple(g(i + _sage_const_1 ) - _sage_const_1  for i in range(n)))
    mats = [_perm_matrix_qn_from_images(img, n) for img in gen_images]

    return {
        "vertices": vertices,
        "n": n,
        "all_group": all_group,
        "all_order": all_order,
        "gens": gens,
        "gen_group": gen_group,
        "mats": mats,
    }


def run_a5_geo_case():
    data = build_a5_geo_data()
    n = data["n"]
    all_order = data["all_order"]
    gen_group = data["gen_group"]
    mats = data["mats"]

    vertices_preserved = all_order >= _sage_const_60 
    isomorphic_to_a5 = gen_group.is_isomorphic(AlternatingGroup(_sage_const_5 ))

    one = vector(QQ, [_sage_const_1 ] * n)
    W_triv_basis = [one]
    W_sumzero_basis = build_sumzero_basis(n)

    inv_triv = is_invariant_subspace(mats, W_triv_basis)
    inv_sumzero = is_invariant_subspace(mats, W_sumzero_basis)

    V = VectorSpace(QQ, n)
    W_triv = span(W_triv_basis)
    W_sumzero = span(W_sumzero_basis)
    inter_dim = W_triv.intersection(W_sumzero).dimension()
    sum_space = W_triv + W_sumzero
    sum_dim = sum_space.dimension()
    inv_sum = is_invariant_subspace(mats, sum_space.basis())

    print("mode: a5_geo")
    print("a5_geo = rotational icosahedral/dodecahedral symmetry group, isomorphic to A5")
    print("note: this is not the full Ih group")
    print(f"group order: {gen_group.order()}")
    print(f"all detected rotational symmetries (order): {all_order}")
    print(f"vertices preserved: {vertices_preserved}")
    print(f"compatible with A5: {isomorphic_to_a5}")
    print(f"W_triv invariant: {inv_triv}")
    print(f"W_sumzero invariant: {inv_sumzero}")
    print(f"direct sum dimension: {sum_dim}")
    print(f"intersection dimension: {inter_dim}")
    print(f"sum invariant: {inv_sum}")
    print(f"dim(V): {V.dimension()}")


def run_a5_geo_decompose_case():
    data = build_a5_geo_data()
    G = data["gen_group"]
    n = data["n"]

    decomp = _character_decomposition_data(G, n)
    class_sizes = decomp["class_sizes"]
    class_orders = decomp["class_orders"]
    fixpoints = decomp["fixpoints"]
    perm_char = decomp["perm_char"]
    degrees = decomp["degrees"]
    mults = decomp["multiplicities"]
    dim_sum = decomp["dim_sum"]
    trivial_mult = decomp["trivial_mult"]
    compatible_a5 = G.is_isomorphic(AlternatingGroup(_sage_const_5 ))

    print("mode: a5_geo_decompose")
    print("a5_geo = rotational icosahedral/dodecahedral symmetry group, isomorphic to A5")
    print("note: this is not the full Ih group")
    print(f"group order: {G.order()}")
    print(f"compatible with A5: {compatible_a5}")
    print(f"class sizes: {class_sizes}")
    print(f"class orders: {class_orders}")
    print(f"fixed points by class: {fixpoints}")
    print(f"character vector (permutation, dim {n}): {perm_char}")
    print(f"irreducible degrees: {degrees}")
    print(f"irreducible multiplicities: {mults}")
    print(f"dimension sum from decomposition: {dim_sum}")
    print(f"trivial multiplicity: {trivial_mult}")
    print(f"dimension check equals {n}: {dim_sum == n}")
    print(f"trivial appears with multiplicity 1: {trivial_mult == _sage_const_1 }")


def _character_decomposition_data(G, n):
    reps = G.conjugacy_classes_representatives()
    class_sizes = [G.conjugacy_class(r).cardinality() for r in reps]
    class_orders = [r.order() for r in reps]
    fixpoints = [sum(_sage_const_1  for i in range(_sage_const_1 , n + _sage_const_1 ) if r(i) == i) for r in reps]
    perm_char = fixpoints

    CT = G.character_table()  # rows: irreducible characters, cols: conjugacy classes
    n_irred = CT.nrows()
    n_classes = CT.ncols()
    if n_classes != len(reps):
        raise RuntimeError("Character table class count mismatch.")

    mults = []
    degrees = [int(CT[i, _sage_const_0 ]) for i in range(n_irred)]
    for i in range(n_irred):
        total = _sage_const_0 
        for j in range(n_classes):
            total += class_sizes[j] * perm_char[j] * CT[i, j].conjugate()
        m = total / G.order()
        m_c = complex(CC(m))
        if abs(m_c.imag) > _sage_const_1en8 :
            raise RuntimeError(f"Non-real multiplicity encountered: {m}")
        m_int = int(round(m_c.real))
        if abs(m_c.real - m_int) > _sage_const_1en8 :
            raise RuntimeError(f"Non-integral multiplicity encountered: {m}")
        mults.append(m_int)

    dim_sum = sum(mults[i] * degrees[i] for i in range(n_irred))
    trivial_mult = mults[_sage_const_0 ] if mults else None

    return {
        "reps": reps,
        "class_sizes": class_sizes,
        "class_orders": class_orders,
        "fixpoints": fixpoints,
        "perm_char": perm_char,
        "character_table": CT,
        "degrees": degrees,
        "multiplicities": mults,
        "dim_sum": dim_sum,
        "trivial_mult": trivial_mult,
    }


def run_a5_geo_projectors_case():
    data = build_a5_geo_data()
    G = data["gen_group"]
    n = data["n"]
    decomp = _character_decomposition_data(G, n)
    CT = decomp["character_table"]
    degrees = decomp["degrees"]
    mults = decomp["multiplicities"]
    dim_sum = decomp["dim_sum"]
    trivial_mult = decomp["trivial_mult"]

    # class index for each group element
    classes = G.conjugacy_classes()
    class_index = {}
    for idx, cl in enumerate(classes):
        for g in cl:
            class_index[g] = idx

    K = CyclotomicField(_sage_const_5 )
    elems = G.list()
    rho = {}
    for g in elems:
        img = tuple(g(i + _sage_const_1 ) - _sage_const_1  for i in range(n))
        rho[g] = matrix(K, _perm_matrix_qn_from_images(img, n))

    # only irreducibles that appear in this representation
    irred_indices = [i for i, m in enumerate(mults) if m > _sage_const_0 ]
    projectors = []
    ranks = []
    for i in irred_indices:
        P = matrix(K, n, n, _sage_const_0 )
        for g in elems:
            j = class_index[g.inverse()]
            chi = K(CT[i, j])
            P += chi * rho[g]
        P *= K(degrees[i]) / K(G.order())
        projectors.append(P)
        ranks.append(P.rank())

    # checks
    idempotence_ok = all((P * P) == P for P in projectors)
    orthogonality_ok = True
    zeroM = matrix(K, n, n, _sage_const_0 )
    for a in range(len(projectors)):
        for b in range(len(projectors)):
            if a == b:
                continue
            if projectors[a] * projectors[b] != zeroM:
                orthogonality_ok = False
                break
        if not orthogonality_ok:
            break
    sum_projector = matrix(K, n, n, _sage_const_0 )
    for P in projectors:
        sum_projector += P
    identity_ok = sum_projector == identity_matrix(K, n)

    rank_targets = [degrees[i] * mults[i] for i in irred_indices]
    rank_check = ranks == rank_targets
    decomposition_ok = (dim_sum == n and trivial_mult == _sage_const_1 )

    print("mode: a5_geo_projectors")
    print("a5_geo = rotational icosahedral/dodecahedral symmetry group, isomorphic to A5")
    print("note: this is not the full Ih group")
    print(f"group order: {G.order()}")
    print(f"decomposition multiplicities: {mults}")
    print(f"decomposition degrees: {degrees}")
    print(f"decomposition used (indices): {irred_indices}")
    print(f"decomposition check (dim=12 & trivial mult=1): {decomposition_ok}")
    print(f"projector idempotence: {idempotence_ok}")
    print(f"projector orthogonality: {orthogonality_ok}")
    print(f"projector ranks: {ranks}")
    print(f"projector rank targets: {rank_targets}")
    print(f"rank check: {rank_check}")
    print(f"sum of projectors = identity: {identity_ok}")


def _build_a5_geo_projectors():
    data = build_a5_geo_data()
    G = data["gen_group"]
    n = data["n"]
    decomp = _character_decomposition_data(G, n)
    CT = decomp["character_table"]
    degrees = decomp["degrees"]
    mults = decomp["multiplicities"]

    classes = G.conjugacy_classes()
    class_index = {}
    for idx, cl in enumerate(classes):
        for g in cl:
            class_index[g] = idx

    K = CyclotomicField(_sage_const_5 )
    elems = G.list()
    rho = {}
    for g in elems:
        img = tuple(g(i + _sage_const_1 ) - _sage_const_1  for i in range(n))
        rho[g] = matrix(K, _perm_matrix_qn_from_images(img, n))

    irred_indices = [i for i, m in enumerate(mults) if m > _sage_const_0 ]
    projectors = []
    for i in irred_indices:
        P = matrix(K, n, n, _sage_const_0 )
        for g in elems:
            j = class_index[g.inverse()]
            chi = K(CT[i, j])
            P += chi * rho[g]
        P *= K(degrees[i]) / K(G.order())
        projectors.append(P)

    return {
        "data": data,
        "decomp": decomp,
        "K": K,
        "irred_indices": irred_indices,
        "projectors": projectors,
    }


def _energy(v):
    return (v.dot_product(v))


def _mode_energies(v, projectors):
    comps = [P * v for P in projectors]
    return [CC(_energy(c)).real() for c in comps], comps


def _find_antipodal_pair(vertices, tol=_sage_const_1en8 ):
    for i, v in enumerate(vertices):
        for j, w in enumerate(vertices):
            if i == j:
                continue
            if (v + w).norm() < tol:
                return i, j
    raise RuntimeError("No antipodal vertex pair found.")


def _all_antipodal_pairs(vertices, tol=_sage_const_1en8 ):
    pairs = []
    used = set()
    for i, v in enumerate(vertices):
        if i in used:
            continue
        found = None
        for j, w in enumerate(vertices):
            if i == j or j in used:
                continue
            if (v + w).norm() < tol:
                found = j
                break
        if found is None:
            raise RuntimeError("Could not complete antipodal pairing.")
        pairs.append((i, found))
        used.add(i)
        used.add(found)
    return pairs


def _icosahedron_adjacency(vertices, tol=_sage_const_1en8 ):
    n = len(vertices)
    dmin = None
    for i in range(n):
        for j in range(i + _sage_const_1 , n):
            d = (vertices[i] - vertices[j]).norm()
            if d > tol and (dmin is None or d < dmin):
                dmin = d
    if dmin is None:
        raise RuntimeError("Could not determine edge length.")

    adj = {i: set() for i in range(n)}
    for i in range(n):
        for j in range(i + _sage_const_1 , n):
            d = (vertices[i] - vertices[j]).norm()
            if abs(d - dmin) < _sage_const_1en6 :
                adj[i].add(j)
                adj[j].add(i)
    return adj


def _connected_triple_cover(vertices):
    """
    Deterministic toy embedding with 4 connected triples in the edge graph.
    """
    adj = _icosahedron_adjacency(vertices)
    unused = set(range(len(vertices)))
    groups = []

    while len(groups) < _sage_const_4  and unused:
        # deterministic seed: smallest index
        a = min(unused)
        nb = sorted([x for x in adj[a] if x in unused])
        if len(nb) < _sage_const_2 :
            # fallback: any two remaining
            rem = sorted(unused - {a})
            if len(rem) < _sage_const_2 :
                break
            b, c = rem[_sage_const_0 ], rem[_sage_const_1 ]
        else:
            b = nb[_sage_const_0 ]
            # choose c adjacent to a and preferably to b as well
            candidates = [x for x in nb[_sage_const_1 :] if b in adj[x]]
            c = candidates[_sage_const_0 ] if candidates else nb[_sage_const_1 ]
        g = [a, b, c]
        for x in g:
            if x in unused:
                unused.remove(x)
        groups.append(g)

    if len(groups) != _sage_const_4 :
        raise RuntimeError("Could not build 4 connected triples for face-neighbor toy embedding.")
    return groups


def _vector_from_groups(groups, order_labels, n):
    code = {"A": _sage_const_3 , "B": _sage_const_2 , "C": _sage_const_1 , "E": _sage_const_0 }
    vals = [_sage_const_0 ] * n
    for gi, idxs in enumerate(groups):
        label = order_labels[gi]
        for idx in idxs:
            vals[idx] = code[label]
    return vector(QQ, vals)


def _center_vector(v):
    n = len(v)
    ones = vector(QQ, [_sage_const_1 ] * n)
    mean_v = QQ(sum(v)) / QQ(n)
    return vector(QQ, list(v - mean_v * ones))


def run_a5_geo_mode_fingerprints_case():
    payload = _build_a5_geo_projectors()
    data = payload["data"]
    K = payload["K"]
    irred_indices = payload["irred_indices"]
    projectors = payload["projectors"]
    n = data["n"]

    # helper to create vectors in K^n
    def vk(entries):
        return vector(K, entries)

    ones = vk([_sage_const_1 ] * n)
    e0 = vk([_sage_const_1 ] + [_sage_const_0 ] * (n - _sage_const_1 ))

    i, j = _find_antipodal_pair(data["vertices"])
    antipodal = vk([_sage_const_1  if k == i else (-_sage_const_1  if k == j else _sage_const_0 ) for k in range(n)])

    rnd = vector(QQ, [_sage_const_2 , -_sage_const_1 , _sage_const_3 , -_sage_const_2 , _sage_const_0 , _sage_const_1 , -_sage_const_3 , _sage_const_4 , -_sage_const_4 , _sage_const_2 , -_sage_const_1 , -_sage_const_1 ])  # sum = 0
    random_sumzero = vk(list(rnd))

    tests = [
        ("all_ones_barycentric", ones),
        ("single_vertex_indicator", e0),
        ("antipodal_pair_difference", antipodal),
        ("random_rational_sumzero", random_sumzero),
    ]

    print("mode: a5_geo_mode_fingerprints")
    print("a5_geo = rotational icosahedral/dodecahedral symmetry group, isomorphic to A5")
    print("note: this is not the full Ih group")
    print(f"group order: {data['gen_group'].order()}")
    print(f"projector components (irred indices): {irred_indices}")

    for name, v in tests:
        energies, comps = _mode_energies(v, projectors)
        total_energy = CC(_energy(v)).real()
        recon = sum(comps, vector(K, [_sage_const_0 ] * n))
        recon_ok = (recon == v)
        energy_ok = abs(sum(energies) - total_energy) < _sage_const_1en7 
        print(f"--- test: {name} ---")
        print(f"sum(v) = {sum(v)}")
        print(f"energies by mode: {energies}")
        print(f"total energy: {total_energy}")
        print(f"reconstruction ok: {recon_ok}")
        print(f"energy sum ok: {energy_ok}")


def _build_symbol_vector(pattern_labels, n):
    """
    Baut einen toy-Signaturvektor aus Labeln (A,B,C,E) mit
    defensiver numerischer Kodierung.
    """
    code = {"A": _sage_const_3 , "B": _sage_const_2 , "C": _sage_const_1 , "E": _sage_const_0 }
    vals = [code[pattern_labels[i % len(pattern_labels)]] for i in range(n)]
    return vector(QQ, vals)


def run_a5_geo_eabc_signature_modes_case():
    payload = _build_a5_geo_projectors()
    data = payload["data"]
    K = payload["K"]
    irred_indices = payload["irred_indices"]
    projectors = payload["projectors"]
    n = data["n"]

    # Defensives toy embedding: zyklische Labelzuweisung ueber Vertex-Indizes.
    v_abce_raw = _build_symbol_vector(["A", "B", "C", "E"], n)
    v_ceab_raw = _build_symbol_vector(["C", "E", "A", "B"], n)

    # Zentrierung (sum-zero) fuer Modenvergleich ohne dominanten trivialen Shift.
    ones = vector(QQ, [_sage_const_1 ] * n)
    mean_abce = QQ(sum(v_abce_raw)) / QQ(n)
    mean_ceab = QQ(sum(v_ceab_raw)) / QQ(n)
    v_abce = vector(QQ, list(v_abce_raw - mean_abce * ones))
    v_ceab = vector(QQ, list(v_ceab_raw - mean_ceab * ones))

    vectors = [
        ("ABCE_raw", vector(K, list(v_abce_raw))),
        ("CEAB_raw", vector(K, list(v_ceab_raw))),
        ("ABCE_centered", vector(K, list(v_abce))),
        ("CEAB_centered", vector(K, list(v_ceab))),
    ]

    print("mode: a5_geo_eabc_signature_modes")
    print("a5_geo = rotational icosahedral/dodecahedral symmetry group, isomorphic to A5")
    print("note: this is not the full Ih group")
    print("embedding note: toy cyclic label-to-vertex map (not canonical geometric EABC map)")
    print(f"group order: {data['gen_group'].order()}")
    print(f"projector components (irred indices): {irred_indices}")

    energy_map = {}
    for name, v in vectors:
        energies, comps = _mode_energies(v, projectors)
        total_energy = CC(_energy(v)).real()
        recon = sum(comps, vector(K, [_sage_const_0 ] * n))
        recon_ok = (recon == v)
        energy_ok = abs(sum(energies) - total_energy) < _sage_const_1en7 
        energy_map[name] = energies
        print(f"--- test: {name} ---")
        print(f"sum(v) = {sum(v)}")
        print(f"energies by mode: {energies}")
        print(f"total energy: {total_energy}")
        print(f"reconstruction ok: {recon_ok}")
        print(f"energy sum ok: {energy_ok}")

    # Chiralitaetsdiagnostik auf den zentrierten Vektoren (3 vs 3')
    e_abce = energy_map["ABCE_centered"]
    e_ceab = energy_map["CEAB_centered"]
    # mode ordering from decompose run: [1,3,3',5] (indices [0,1,2,4])
    d3 = e_abce[_sage_const_1 ] - e_ceab[_sage_const_1 ]
    d3p = e_abce[_sage_const_2 ] - e_ceab[_sage_const_2 ]
    print("--- comparison: centered ABCE vs CEAB ---")
    print(f"delta energy in 3-mode: {d3}")
    print(f"delta energy in 3'-mode: {d3p}")


def run_a5_geo_eabc_embedding_sweep_case():
    payload = _build_a5_geo_projectors()
    data = payload["data"]
    K = payload["K"]
    projectors = payload["projectors"]
    n = data["n"]
    vertices = data["vertices"]

    # Embedding families
    embeddings = []

    # 1) cyclic baseline
    cyc_groups = [[i for i in range(k, n, _sage_const_4 )] for k in range(_sage_const_4 )]
    embeddings.append(("cyclic", cyc_groups))

    # 2) antipodal-pair based embedding: 6 pairs -> 4 groups of size 3
    pairs = _all_antipodal_pairs(vertices)
    anti_groups = [[], [], [], []]
    pair_schedule = [_sage_const_0 , _sage_const_1 , _sage_const_2 , _sage_const_3 , _sage_const_0 , _sage_const_1 ]  # gives 3,3,3,3 vertices after splitting pairs
    for pidx, (u, v) in enumerate(pairs):
        g = pair_schedule[pidx]
        anti_groups[g].append(u)
        anti_groups[(g + _sage_const_2 ) % _sage_const_4 ].append(v)
    embeddings.append(("antipodal", anti_groups))

    # 3) face-neighbor toy embedding
    face_groups = _connected_triple_cover(vertices)
    embeddings.append(("face_neighbor", face_groups))

    # 4) random balanced embeddings (deterministic seed)
    rng = py_random.Random(int(_sage_const_20260703 ))
    base = list(range(n))
    for t in range(_sage_const_12 ):
        rng.shuffle(base)
        g = [base[_sage_const_0 :_sage_const_3 ], base[_sage_const_3 :_sage_const_6 ], base[_sage_const_6 :_sage_const_9 ], base[_sage_const_9 :_sage_const_12 ]]
        embeddings.append((f"random_balanced_{t+_sage_const_1 }", g))

    eps = _sage_const_1en9 
    same_count = _sage_const_0 
    max_d3 = _sage_const_0p0 
    max_d3p = _sage_const_0p0 

    print("mode: a5_geo_eabc_embedding_sweep")
    print("a5_geo = rotational icosahedral/dodecahedral symmetry group, isomorphic to A5")
    print("note: this is not the full Ih group")
    print("embedding note: toy embedding families, no canonical EABC->icosahedron map claimed")
    print(f"group order: {data['gen_group'].order()}")

    for name, groups in embeddings:
        v_abce_raw = _vector_from_groups(groups, ["A", "B", "C", "E"], n)
        v_ceab_raw = _vector_from_groups(groups, ["C", "E", "A", "B"], n)
        v_abce = _center_vector(v_abce_raw)
        v_ceab = _center_vector(v_ceab_raw)

        e_abce, comps_abce = _mode_energies(vector(K, list(v_abce)), projectors)
        e_ceab, comps_ceab = _mode_energies(vector(K, list(v_ceab)), projectors)
        d = [e_abce[i] - e_ceab[i] for i in range(len(e_abce))]
        same = all(abs(x) < eps for x in d)
        same_count += _sage_const_1  if same else _sage_const_0 
        max_d3 = max(max_d3, abs(d[_sage_const_1 ]))
        max_d3p = max(max_d3p, abs(d[_sage_const_2 ]))

        recon_abce = sum(comps_abce, vector(K, [_sage_const_0 ] * n)) == vector(K, list(v_abce))
        recon_ceab = sum(comps_ceab, vector(K, [_sage_const_0 ] * n)) == vector(K, list(v_ceab))

        print(f"embedding: {name}")
        print(f"ABCE energies: {e_abce}")
        print(f"CEAB energies: {e_ceab}")
        print(f"delta: {d}")
        print(f"same fingerprint: {same}")
        print(f"reconstruction ABCE: {recon_abce}")
        print(f"reconstruction CEAB: {recon_ceab}")

    total = len(embeddings)
    print("summary:")
    print(f"tested embeddings: {total}")
    print(f"identical fingerprints: {same_count}")
    print(f"non-identical fingerprints: {total - same_count}")
    print(f"max |delta E3|: {max_d3}")
    print(f"max |delta E3'|: {max_d3p}")


def _is_graph_triangle(adj, triple):
    a, b, c = triple
    return b in adj[a] and c in adj[a] and c in adj[b]


def _check_musketiere_neighbor_triple(vertices, groups, order_labels):
    """
    Prueft pro Trägerkanal, ob ein Musketiere-Nachbar-Dreier existiert:
    - Dreieck im Kantengraph
    - Labels = die drei Nicht-Träger-Kanaele
    - mindestens eine Kante zum Träger-Dreier
    """
    from itertools import combinations

    adj = _icosahedron_adjacency(vertices)
    n = len(vertices)
    labels = [None] * n
    for gi, idxs in enumerate(groups):
        for idx in idxs:
            labels[idx] = order_labels[gi]

    channels = ["E", "A", "B", "C"]
    host_triples = {}
    for gi, idxs in enumerate(groups):
        host_triples[order_labels[gi]] = set(idxs)

    per_host = {}
    for host in channels:
        others = {c for c in channels if c != host}
        carrier = host_triples[host]
        found = False
        witness = None
        for triple in combinations(range(n), _sage_const_3 ):
            if not _is_graph_triangle(adj, triple):
                continue
            tlabels = {labels[i] for i in triple}
            if tlabels != others:
                continue
            touches = any(
                nb in carrier
                for v in triple
                for nb in adj[v]
            )
            if touches:
                found = True
                witness = triple
                break
        per_host[host] = {"ok": found, "witness": witness}
    return all(v["ok"] for v in per_host.values()), per_host


def _canonical_vertex_sort(vertices):
    """Deterministische Ikosaeder-Eckenordnung (lexikographisch auf gerundeten Koordinaten)."""
    indexed = list(enumerate(vertices))
    indexed.sort(key=lambda iv: tuple(round(float(x), _sage_const_8 ) for x in iv[_sage_const_1 ]))
    return [i for i, _ in indexed]


def _zero_axis_index(v, tol=_sage_const_1en8 ):
    for j in range(_sage_const_3 ):
        if abs(v[j]) < tol:
            return j
    return None


def _build_canonical_eabc_embedding(vertices):
    """
    Kanonisches EABC-Embedding (Projekt „Die drei Musketiere“).

    K1: lexikographische Vertex-Sortierung
    K2: mod-4-Orbit-Partition auf sortierten Indizes
    K3: E-Saal = Orbit mit maximaler x=0-Dichte (Mittelachse)
    K4: chi-Label E->A->C->B mit deterministischem Tie-Break
    """
    n = len(vertices)
    perm = _canonical_vertex_sort(vertices)
    groups = [[perm[i] for i in range(k, n, _sage_const_4 )] for k in range(_sage_const_4 )]

    def e_score(group):
        return sum(_sage_const_1  for idx in group if _zero_axis_index(vertices[idx]) == _sage_const_0 )

    scores = [e_score(g) for g in groups]
    orbit_order = sorted(range(_sage_const_4 ), key=lambda i: (-scores[i], min(groups[i])))
    chi_labels = ["E", "A", "C", "B"]
    label_by_orbit = {orbit_order[i]: chi_labels[i] for i in range(_sage_const_4 )}
    order_labels = [label_by_orbit[i] for i in range(_sage_const_4 )]

    meta = {
        "vertex_sort": perm,
        "orbit_e_scores": scores,
        "orbit_order": orbit_order,
        "chi_labels": chi_labels,
    }
    return groups, order_labels, meta


def _label_code_vector(groups, order_labels):
    code = {"E": _sage_const_0 , "A": _sage_const_1 , "B": _sage_const_2 , "C": _sage_const_3 }
    n = max(max(g) for g in groups) + _sage_const_1 
    vec = [-_sage_const_1 ] * n
    for gi, idxs in enumerate(groups):
        for idx in idxs:
            vec[idx] = code[order_labels[gi]]
    return tuple(vec)


def _chi_rotate_label_code(code):
    chi = {_sage_const_0 : _sage_const_1 , _sage_const_1 : _sage_const_3 , _sage_const_3 : _sage_const_2 , _sage_const_2 : _sage_const_0 }  # E->A->C->B->E
    return tuple(chi[x] for x in code)


def _label_codes_chi_equivalent(a, b):
    cur = a
    for _ in range(_sage_const_4 ):
        if cur == b:
            return True
        cur = _chi_rotate_label_code(cur)
    return False


def _permuted_label_code(base_code, perm_images):
    n = len(base_code)
    out = [-_sage_const_1 ] * n
    for i in range(n):
        out[perm_images[i]] = base_code[i]
    return tuple(out)


def _collect_toy_embeddings(vertices):
    embeddings = []

    cyc_groups = [[i for i in range(k, _sage_const_12 , _sage_const_4 )] for k in range(_sage_const_4 )]
    embeddings.append(("cyclic", cyc_groups, ["E", "A", "B", "C"]))

    pairs = _all_antipodal_pairs(vertices)
    anti_groups = [[], [], [], []]
    pair_schedule = [_sage_const_0 , _sage_const_1 , _sage_const_2 , _sage_const_3 , _sage_const_0 , _sage_const_1 ]
    for pidx, (u, v) in enumerate(pairs):
        g = pair_schedule[pidx]
        anti_groups[g].append(u)
        anti_groups[(g + _sage_const_2 ) % _sage_const_4 ].append(v)
    embeddings.append(("antipodal", anti_groups, ["E", "A", "B", "C"]))

    face_groups = _connected_triple_cover(vertices)
    embeddings.append(("face_neighbor", face_groups, ["E", "A", "B", "C"]))

    rng = py_random.Random(int(_sage_const_20260703 ))
    base = list(range(_sage_const_12 ))
    for t in range(_sage_const_12 ):
        rng.shuffle(base)
        g = [base[_sage_const_0 :_sage_const_3 ], base[_sage_const_3 :_sage_const_6 ], base[_sage_const_6 :_sage_const_9 ], base[_sage_const_9 :_sage_const_12 ]]
        embeddings.append((f"random_balanced_{t+_sage_const_1 }", g, ["E", "A", "B", "C"]))

    return embeddings


def _canonical_adj_dict():
    """
    Hart kodierter Ikosaeder-Graph auf Vertex-Indizes 0..11 (E-029 / Lean).
    """
    edges = [
        (_sage_const_0 , _sage_const_1 ), (_sage_const_0 , _sage_const_2 ), (_sage_const_0 , _sage_const_6 ), (_sage_const_0 , _sage_const_7 ), (_sage_const_0 , _sage_const_8 ),
        (_sage_const_1 , _sage_const_2 ), (_sage_const_1 , _sage_const_3 ), (_sage_const_1 , _sage_const_5 ), (_sage_const_1 , _sage_const_7 ),
        (_sage_const_2 , _sage_const_4 ), (_sage_const_2 , _sage_const_5 ), (_sage_const_2 , _sage_const_6 ),
        (_sage_const_3 , _sage_const_5 ), (_sage_const_3 , _sage_const_7 ), (_sage_const_3 , _sage_const_9 ), (_sage_const_3 , _sage_const_11 ),
        (_sage_const_4 , _sage_const_5 ), (_sage_const_4 , _sage_const_6 ), (_sage_const_4 , _sage_const_9 ), (_sage_const_4 , _sage_const_10 ),
        (_sage_const_5 , _sage_const_9 ),
        (_sage_const_6 , _sage_const_8 ), (_sage_const_6 , _sage_const_10 ),
        (_sage_const_7 , _sage_const_8 ), (_sage_const_7 , _sage_const_11 ),
        (_sage_const_8 , _sage_const_10 ), (_sage_const_8 , _sage_const_11 ),
        (_sage_const_9 , _sage_const_10 ), (_sage_const_9 , _sage_const_11 ),
        (_sage_const_10 , _sage_const_11 ),
    ]
    adj = {i: set() for i in range(_sage_const_12 )}
    for a, b in edges:
        adj[a].add(b)
        adj[b].add(a)
    return adj


def _canonical_graph():
    adj = _canonical_adj_dict()
    edges = sorted({tuple(sorted((u, v))) for u in adj for v in adj[u]})
    return Graph(edges, format="list_of_edges")


def _perm_image0(permutation, vertex):
    """Bild eines 0-basierten Vertex-Index unter Sage-Permutation (1-basiert)."""
    return int(permutation(vertex + _sage_const_1 )) - _sage_const_1 


def _apply_channel_perm(tau, channel):
    """Wende S4-Permutation auf Kanalcode 0..3 an (E=0, A=1, B=2, C=3)."""
    return int(tau(channel + _sage_const_1 )) - _sage_const_1 


def _label_code_equivalent(toy_code, canonical_code, sigma, tau):
    """
    Lean-Konvention (E-031): L[v] = tau(canonicalLabelCode[sigma(v)]).
    """
    for v in range(_sage_const_12 ):
        sigma_v = _perm_image0(sigma, v)
        if toy_code[v] != _apply_channel_perm(tau, canonical_code[sigma_v]):
            return False
    return True


def _code_from_equivalence(canonical_code, sigma, tau):
    return tuple(
        _apply_channel_perm(tau, canonical_code[_perm_image0(sigma, v)])
        for v in range(_sage_const_12 )
    )


def _sigma_as_tuple(sigma):
    return tuple(_perm_image0(sigma, v) for v in range(_sage_const_12 ))


def _tau_as_tuple(tau):
    return tuple(_apply_channel_perm(tau, c) for c in range(_sage_const_4 ))


def _find_equivalence_witness(toy_code, canonical_code, graph_automs, channel_perms):
    for sigma in graph_automs:
        for tau in channel_perms:
            if _label_code_equivalent(toy_code, canonical_code, sigma, tau):
                return sigma, tau
    return None, None


def _collect_passing_toy_label_codes(vertices):
    """Die 9 Musketiere-bestandenen toy-Embeddings als (name, label_code)."""
    passing = []
    for name, groups, order_labels in _collect_toy_embeddings(vertices):
        ok, _ = _check_musketiere_neighbor_triple(vertices, groups, order_labels)
        if ok:
            passing.append((name, _label_code_vector(groups, order_labels)))
    return passing


def _partitions_match_under_automorphism(part_a, part_b, graph_automs):
    """Prueft, ob eine Vertex-Partition in die andere unter Aut(G) ueberfuehrt wird."""
    norm_a = sorted(tuple(sorted(p)) for p in part_a)
    norm_b = sorted(tuple(sorted(p)) for p in part_b)
    for sigma in graph_automs:
        images = [_perm_image0(sigma, v) for v in range(_sage_const_12 )]
        mapped = sorted(
            tuple(sorted(images[v] for v in part)) for part in part_a
        )
        if mapped == norm_b:
            return True, _sigma_as_tuple(sigma)
    return False, None


def run_a5_geo_canonical_equivalence_case():
    """
    E-031: Prueft IsEquivalentToCanonical in Lean-Richtung auf festem Vertex-Traeger.

    toy_code[v] == tau(canonical_code[sigma(v)])

    Wichtig: Musketiere-bestanden (/9) ist strikt schwaecher als kanonisch-aquivalent.
    Nur Embeddings mit derselben Bremensaal-Partition (mod Aut(G)) koennen Zeugen haben.
    """
    payload = _build_a5_geo_projectors()
    vertices = payload["data"]["vertices"]

    groups, order_labels, _ = _build_canonical_eabc_embedding(vertices)
    canonical_code = _label_code_vector(groups, order_labels)
    canonical_partition = [set(g) for g in groups]

    g_canonical = _canonical_graph()
    graph_automs = g_canonical.automorphism_group()
    channel_perms = list(SymmetricGroup(_sage_const_4 ))

    passing = _collect_passing_toy_label_codes(vertices)

    print("mode: a5_geo_canonical_equivalence")
    print("project: Die drei Musketiere (E-031)")
    print("check: label codes equivalent to canonical via (sigma, tau)")
    print("lean_convention: L[v] = tau(canonical_code[sigma(v)])")
    print(f"canonical_label_code: {canonical_code}")
    print(f"canonical_partition: {[sorted(g) for g in groups]}")
    print(f"graph_automorphisms: {graph_automs.cardinality()}")
    print(f"channel_permutations_S4: {len(channel_perms)}")
    print(f"musketiere_passing_toy_embeddings: {len(passing)}")

    # Sanity: kanonisch ist trivial aequivalent zu sich selbst.
    id_sigma = graph_automs.one()
    id_tau = SymmetricGroup(_sage_const_4 ).one()
    self_ok = _label_code_equivalent(canonical_code, canonical_code, id_sigma, id_tau)
    print(f"canonical_self_equivalent: {self_ok}")

    equivalent_count = _sage_const_0 
    partition_compatible = _sage_const_0 
    results = {}

    for name, toy_code in passing:
        toy_groups = [g for n, g, _ in _collect_toy_embeddings(vertices) if n == name][_sage_const_0 ]
        toy_partition = [set(g) for g in toy_groups]
        part_ok, part_sigma = _partitions_match_under_automorphism(
            toy_partition, canonical_partition, graph_automs
        )
        if part_ok:
            partition_compatible += _sage_const_1 

        sigma, tau = _find_equivalence_witness(
            toy_code, canonical_code, graph_automs, channel_perms
        )
        verified = sigma is not None

        print(f"--- embedding: {name} ---")
        print(f"label_code: {toy_code}")
        print(f"partition: {[sorted(g) for g in toy_groups]}")
        print(f"partition_compatible_with_canonical: {part_ok}")
        if part_ok:
            print(f"partition_witness_sigma: {part_sigma}")

        if not verified:
            print("equivalent: False")
            print("witness: none")
            results[name] = {
                "verified": False,
                "partition_compatible": part_ok,
            }
            continue

        transported = _code_from_equivalence(canonical_code, sigma, tau)
        equivalent_count += _sage_const_1 
        sigma_tuple = _sigma_as_tuple(sigma)
        tau_tuple = _tau_as_tuple(tau)
        results[name] = {
            "verified": True,
            "partition_compatible": part_ok,
            "sigma": sigma_tuple,
            "tau": tau_tuple,
            "transported_code": transported,
            "code_match": transported == toy_code,
        }

        print("equivalent: True")
        print(f"sigma (0-based images): {sigma_tuple}")
        print(f"tau (on channels 0..3): {tau_tuple}")
        print(f"transported_code_match: {transported == toy_code}")

    total = len(passing)
    all_equivalent = equivalent_count == total
    print("--- summary ---")
    print(f"strict_equivalent: {equivalent_count} / {total}")
    print(f"partition_compatible_with_canonical: {partition_compatible} / {total}")
    print(f"all_passing_toys_strict_equivalent: {all_equivalent}")
    print(
        "interpretation: musketiere_pass implies neither partition nor label "
        "equivalence to K1-K4 canonical on fixed indices"
    )

    return all_equivalent, results


def run_a5_geo_chi_objectivity_case():
    payload = _build_a5_geo_projectors()
    vertices = payload["data"]["vertices"]
    groups, order_labels, _ = _build_canonical_eabc_embedding(vertices)
    canonical_code = _label_code_vector(groups, order_labels)

    print("mode: a5_geo_chi_objectivity")
    print("project: Die drei Musketiere (E-030)")
    print("check: chi-relabeling preserves musketiere neighbor triple")

    chi = {_sage_const_0 : _sage_const_1 , _sage_const_1 : _sage_const_3 , _sage_const_3 : _sage_const_2 , _sage_const_2 : _sage_const_0 }
    names = ["E", "A", "B", "C"]

    for power in range(_sage_const_4 ):
        permuted_code = canonical_code
        for _ in range(power):
            permuted_code = _chi_rotate_label_code(permuted_code)
        # build groups/labels from same partition, relabel groups by chi^power
        inv = {n: i for i, n in enumerate(names)}
        new_order = []
        for lab in order_labels:
            c = inv[lab]
            for _ in range(power):
                c = chi[c]
            new_order.append(names[c])
        ok, detail = _check_musketiere_neighbor_triple(vertices, groups, new_order)
        print(f"--- chi_power={power} order_labels={new_order} ---")
        print(f"all_hosts_ok: {ok}")
        for host, info in detail.items():
            print(f"  host={host}: ok={info['ok']}, witness={info['witness']}")

    print("--- summary ---")
    print("chi_orbit_pass: all four powers should be True")


def run_a5_geo_canonical_embedding_case():
    payload = _build_a5_geo_projectors()
    data = payload["data"]
    vertices = data["vertices"]
    gen_group = data["gen_group"]
    n = data["n"]

    groups, order_labels, meta = _build_canonical_eabc_embedding(vertices)
    canonical_code = _label_code_vector(groups, order_labels)
    musk_ok, musk_detail = _check_musketiere_neighbor_triple(vertices, groups, order_labels)

    print("mode: a5_geo_canonical_embedding")
    print("project: Die drei Musketiere")
    print("note: canonical EABC->icosahedron map; fixes gauge of toy embeddings")
    print(f"group order: {gen_group.order()}")
    print("--- canonical construction ---")
    print(f"vertex_sort: {meta['vertex_sort']}")
    print(f"orbit_e_scores (x=0 count): {meta['orbit_e_scores']}")
    print(f"orbit_order (E first): {meta['orbit_order']}")
    print(f"order_labels: {order_labels}")
    print(f"groups: {groups}")
    print(f"label_code: {canonical_code}")
    print(f"musketiere_all_hosts_ok: {musk_ok}")
    for host, info in musk_detail.items():
        print(f"  host={host}: ok={info['ok']}, witness={info['witness']}")

    chi_orbit_hits = _sage_const_0 
    for g in gen_group.list():
        images = tuple(g(i + _sage_const_1 ) - _sage_const_1  for i in range(n))
        permuted = _permuted_label_code(canonical_code, images)
        if _label_codes_chi_equivalent(canonical_code, permuted):
            chi_orbit_hits += _sage_const_1 

    print("--- A5 action on label code ---")
    print(f"chi_orbit_equivalent_under_A5: {chi_orbit_hits} / {gen_group.order()}")

    toy = _collect_toy_embeddings(vertices)
    print("--- toy embedding classification ---")
    canonical_partition = tuple(tuple(sorted(g)) for g in groups)
    pass_count = _sage_const_0 
    same_partition = _sage_const_0 
    chi_match = _sage_const_0 
    for name, tg, tl in toy:
        ok, _ = _check_musketiere_neighbor_triple(vertices, tg, tl)
        if ok:
            pass_count += _sage_const_1 
        part = tuple(tuple(sorted(g)) for g in tg)
        if part == canonical_partition:
            same_partition += _sage_const_1 
        code = _label_code_vector(tg, tl)
        if _label_codes_chi_equivalent(canonical_code, code):
            chi_match += _sage_const_1 
        print(
            f"  {name}: musk_ok={ok}, same_partition={part == canonical_partition}, "
            f"chi_label_match={_label_codes_chi_equivalent(canonical_code, code)}"
        )

    print("--- summary ---")
    print(f"toy_embeddings: {len(toy)}")
    print(f"toy_musk_pass: {pass_count}")
    print(f"toy_same_partition_as_canonical: {same_partition}")
    print(f"toy_chi_label_match: {chi_match}")
    print(
        f"face_neighbor_musk_ok: "
        f"{_check_musketiere_neighbor_triple(vertices, toy[_sage_const_2 ][_sage_const_1 ], toy[_sage_const_2 ][_sage_const_2 ])[_sage_const_0 ]}"
    )


def run_a5_geo_drei_musketiere_case():
    payload = _build_a5_geo_projectors()
    data = payload["data"]
    vertices = data["vertices"]

    embeddings = _collect_toy_embeddings(vertices)
    can_groups, can_labels, _ = _build_canonical_eabc_embedding(vertices)
    embeddings.append(("canonical", can_groups, can_labels))

    total = _sage_const_0 
    passed = _sage_const_0 
    host_failures = {"E": _sage_const_0 , "A": _sage_const_0 , "B": _sage_const_0 , "C": _sage_const_0 }

    print("mode: a5_geo_drei_musketiere")
    print("project: Die drei Musketiere")
    print("check: Musketiere-Nachbar-Dreier pro Bremensaal (Trägerkanal)")
    print(f"group order: {data['gen_group'].order()}")

    for name, groups, order_labels in embeddings:
        ok, per_host = _check_musketiere_neighbor_triple(vertices, groups, order_labels)
        total += _sage_const_1 
        if ok:
            passed += _sage_const_1 
        else:
            for host, info in per_host.items():
                if not info["ok"]:
                    host_failures[host] += _sage_const_1 
        print(f"--- embedding: {name} ---")
        print(f"all_hosts_ok: {ok}")
        for host, info in per_host.items():
            print(f"  host={host}: ok={info['ok']}, witness={info['witness']}")

    print("--- summary ---")
    print(f"embeddings_tested: {total}")
    print(f"embeddings_all_pass: {passed}")
    print(f"host_failures: {host_failures}")


def main():
    mode = "a4"
    if len(sys.argv) > _sage_const_1 :
        mode = sys.argv[_sage_const_1 ].strip().lower()

    if mode == "a4":
        run_perm_case(_sage_const_4 )
    elif mode == "a5":
        run_perm_case(_sage_const_5 )
    elif mode == "a5_geo":
        run_a5_geo_case()
    elif mode == "a5_geo_decompose":
        run_a5_geo_decompose_case()
    elif mode == "a5_geo_projectors":
        run_a5_geo_projectors_case()
    elif mode == "a5_geo_mode_fingerprints":
        run_a5_geo_mode_fingerprints_case()
    elif mode == "a5_geo_eabc_signature_modes":
        run_a5_geo_eabc_signature_modes_case()
    elif mode == "a5_geo_eabc_embedding_sweep":
        run_a5_geo_eabc_embedding_sweep_case()
    elif mode == "a5_geo_drei_musketiere":
        run_a5_geo_drei_musketiere_case()
    elif mode == "a5_geo_canonical_embedding":
        run_a5_geo_canonical_embedding_case()
    elif mode == "a5_geo_chi_objectivity":
        run_a5_geo_chi_objectivity_case()
    elif mode == "a5_geo_canonical_equivalence":
        run_a5_geo_canonical_equivalence_case()
    else:
        print(
            "Unbekannter Modus. Nutze: "
            "a4 | a5 | a5_geo | a5_geo_decompose | a5_geo_projectors | "
            "a5_geo_mode_fingerprints | a5_geo_eabc_signature_modes | "
            "a5_geo_eabc_embedding_sweep | a5_geo_drei_musketiere | "
            "a5_geo_canonical_embedding | a5_geo_chi_objectivity | "
            "a5_geo_canonical_equivalence"
        )
        raise SystemExit(_sage_const_2 )


if __name__ == "__main__":
    main()

